server {
    listen 80;
    server_name __SERVER_NAME__;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name __SERVER_NAME__;

    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    index index.php index.html;
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;

	# Handle PHP Files
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Handle Static Files and Fallback to Laravel Routes
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;  # Serve pre-compressed files if available
    }

    # Enable Gzip Compression
    gzip on;
    gzip_types text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_proxied any;
    gzip_min_length 1000;
    gzip_comp_level 6;
    gzip_vary on;

    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
