
  worker:
    image: __PROJECT_NAME__
    container_name: __PROJECT_NAME__-worker
    restart: unless-stopped
    working_dir: /var/www/
    user: "${UID:-1000}:${GID:-1000}"
    command: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3"]
    volumes:
      - ./:/var/www
    networks:
      - __PROJECT_NAME__
    depends_on:
      - php
      - redis
